### ISSUE TITLE
[Spiral] Add custom function option as prop to get spiral coordinates 

### ISSUE THREAD

**Issue by lezan** [lucafalasco/datalith#41]
I am not sure about that, but I think responsability has failed with Spiral chart component, in particular with bubble positions.
When you generate spiral coordinates [[1](https://github.com/lucafalasco/datalith/blob/2f972daa72ebe584e1e4de4ba7f6180b0ed3ae7e/packages/datalith-spiral/src/index.tsx#L29)], you are not taking into account width and height, could be a problem?
I think we need to scale up/down coordinates according to actual height an width or they are going to be render outside of container. Or could be an issue related to g transform? [[2](https://github.com/lucafalasco/datalith/blob/2f972daa72ebe584e1e4de4ba7f6180b0ed3ae7e/packages/datalith-spiral/src/index.tsx#L115)] Or maybe because we are not separating correcly wrapper and bounds without taking into account margins?
What do you think about that? Am I missing something?

Thanks!

**Comment by lucafalasco** [comment]
Hi @lezan, thanks for your comment.

The basic idea for each chart is to have the width and height props only control the dimensions of the SVG container, as well as automatically set the center point of the visualization (if not provided). 
This means width and height set on the svg aren’t currently taken into account in the visualization logic. This is mainly to give user the freedom to adjust the size and the position of the elements regardless of the dimensions of the container (maybe you want more space to add additional svg elements for example).

With that being said, I’m well aware of the problem you’re describing with the `Spiral` component, the issue regarding elements which could potentially end up outside of the container bounds is actually something that could happen with almost every chart in the library right now, but it’s also a necessary trade-off to allow the user to have more control over the visualization, so right now it’s up to the user to make sure that all of the elements fit into the container.

I think one thing that can be done though, regarding the Spiral component, is maybe adding a prop to provide a custom function (or maybe even a single value?) to get the spiral coordinates, so that one can control the position of the elements.

Thanks for bringing this up, this project is still at an early stage and every feedback is much appreciated! 😉

**Comment by lezan** [comment]
> 
> 
> Hi @lezan, thanks for your comment.

Thanks for you answer.

> This is mainly to give user the freedom to adjust the size and the position of the elements regardless of the dimensions of the container (maybe you want more space to add additional svg elements for example).

How can I adjust the position of the elements in the Spiral? The only way I found was to change spacing and center according to a window resize event.

> With that being said, I’m well aware of the problem you’re describing with the `Spiral` component, the issue regarding elements which could potentially end up outside of the container bounds is actually something that could happen with almost every chart in the library right now.

That's exactly the issue and what I trying to say before.

> I think one thing that can be done though, regarding the Spiral component, is maybe adding a prop to provide a custom function (or maybe even a single value?) to get the spiral coordinates, so that one can control the position of the elements.

I think a custom function that takes into account width and height could be a solution, but I am not sure about that. When you say to use a single value what are you thinking about?

> Thanks for bringing this up, this project is still at an early stage and every feedback is much appreciated! 😉

Thanks too for this library :).

**Comment by lucafalasco** [comment]
It's not possible to pass a new prop `getSpiralCoords` to Spiral chart in order to have fine-grained control over the positions of the elements.

[Here](https://github.com/lucafalasco/datalith/blob/master/packages/datalith-storybook/src/components/spiral.story.tsx) you can find some examples on how to use it.

**Comment by lucafalasco** [comment]
It's now possible to pass a new prop `getSpiralCoords` to Spiral Chart in order to get fine-grained control over the positions of the elements.

[Here](https://github.com/lucafalasco/datalith/blob/master/packages/datalith-storybook/src/components/spiral.story.tsx) you can find some examples on how to use it.
